definitions:
  ProductRequest:
    properties:
      base_price:
        type: integer
      description:
        type: string
      name:
        type: string
      sell_price:
        type: integer
      stock:
        type: integer
    type: object
  model.Product:
    properties:
      basePrice:
        type: integer
      createdAt:
        type: string
      description:
        type: string
      id:
        type: string
      isActive:
        type: boolean
      name:
        type: string
      sellPrice:
        type: integer
      stock:
        type: integer
      updatedAt:
        type: string
    type: object
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
paths:
  /product:
    post:
      consumes:
      - application/json
      description: post create product
      parameters:
      - description: Product
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/ProductRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Product'
      summary: post product
      tags:
      - Product
  /product/{id}:
    get:
      consumes:
      - application/json
      description: get detail product
      parameters:
      - description: uuid
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Product'
      summary: get product
      tags:
      - Product
swagger: "2.0"
